### ISSUE TITLE
No sync between bill shown on home page and the mess bill section

### ISSUE THREAD

**Issue by divc13** [Ashu3208/MessAutomationSystem#12]
Different bill amounts are shown on home page and mess bill section of same student. 

![image](https://user-images.githubusercontent.com/110289042/230549467-638438c2-ab91-496c-8040-1ec49af9af88.png)

![image](https://user-images.githubusercontent.com/110289042/230549474-f7fe2071-0ccb-4bc8-aeb8-c31064b36564.png)

**Comment by chethan58** [comment]
The mess bill page shows user's past bills. where each bill contains
from which date till which date the bill is for
number of working days between the dates 
daily cost for the each working day between the dates
number of rebate days of the user between the dates 
extras cost which corresponds to the extras user ordered between the dates 
 and the total amount.

home page shows
dues which is the total amount user yet to pay till date.
rebate days shows the number of rebate days that are not considered yet in any of user's bills.
extras cost shows the amount of extras user ordered which is not billed yet.
when manager generates the bill above  extras cost  and rebate days are considered in the bill and later set to 0 , and the total amount of the generated bill will be added to dues .

given the functionality of home page and mess bill page , the case u mentioned does not seem to be an issue for me .please elaborate

**Comment by divc13** [comment]
I apologize for this, I did not think in the way you explianed.
