### ISSUE TITLE
Invalid input in Rebate Request

### ISSUE THREAD

**Issue by Divyanshsingh1910** [Ashu3208/MessAutomationSystem#14]
Students can request rebates from x1 date to x2, where x1>x2.
![image](https://user-images.githubusercontent.com/103668090/230549927-0545f3b2-657f-46bd-90c2-13acb0724c82.png)

**Comment by Ashu3208** [comment]
This has been resolved

**Comment by chethan58** [comment]
no the student cannot req with end date less than start date i.e.., if he requests so, that will not considered and not reflected in user's my rebate requests . if that's not what u mean then please elaborate.
