### ISSUE TITLE
Front end issue on long complaint

### ISSUE THREAD

**Issue by divc13** [Ashu3208/MessAutomationSystem#16]
When user gives long complaint, the front end gets destroyed.

![image](https://user-images.githubusercontent.com/110289042/230551803-a5af16de-5760-4e48-8cd1-48d51f79f57f.png)

![image](https://user-images.githubusercontent.com/110289042/230551808-9432667e-f3b0-49d6-b097-894be27ed464.png)

![WhatsApp Image 2023-04-07 at 11 39 28](https://user-images.githubusercontent.com/110289042/230551930-0834b3b0-879f-494e-9fb0-dc6093331761.jpg)

**Comment by sawanhn** [comment]
this issue has been fixed, please check once and reply if there are any further errors ,else close the issue
