### ISSUE TITLE
Mess manager can give infinitely long input. Add restriction.

### ISSUE THREAD

**Issue by divc13** [Ashu3208/MessAutomationSystem#17]
![WhatsApp Image 2023-04-07 at 11 45 05](https://user-images.githubusercontent.com/110289042/230552725-0a0637e4-89b5-4aba-9710-50224f0b96a7.jpg)

**Comment by divc13** [comment]
This can lead to spam.

**Comment by Ashu3208** [comment]
I understand that mess managers can give infinitely long input but managers are supposed to be a responsible person and can be trusted that they will not do spam.
Please close the issue if satisfied

**Comment by divc13** [comment]
Such inputs may not always be intentional. Hence you should limit the size of reply.

**Comment by chethan58** [comment]
limit is 300 characters now. verify and comment if anything is wrong else close issue.
