### ISSUE TITLE
Frontend error on long reply from mess manager

### ISSUE THREAD

**Issue by divc13** [Ashu3208/MessAutomationSystem#18]
![image](https://user-images.githubusercontent.com/110289042/230552912-e3bfea8e-7a69-42ff-a327-0d58117a97d6.png)

**Comment by chethan58** [comment]
limit is 300 characters now. verify and comment if anything is wrong else close issue.

**Comment by sawanhn** [comment]
this issue has been fixed, please check once and reply if there are any further errors ,else close the issue
