### ISSUE TITLE
Dues Calculation

### ISSUE THREAD

**Issue by Divyanshsingh1910** [Ashu3208/MessAutomationSystem#19]
Scenario: Let's say the student had Rs.150 for dues, then the admin can add Rs.500 paid by the student from the account access option, and even then the updates Dues on the Student Side is Rs.0

**Comment by chethan58** [comment]
the app is supposed to be used by iit kanpur students ,so no student is dumb enough to pay more than required.
so the case u mentioned occurs due to admin error/negligence. we wanted dues to have non negative value . so if the amount entered is greater than dues , dues will be set to 0 rather than negative. comment if u have any alternative else close issue.

**Comment by Divyanshsingh1910** [comment]
@chethan58 it's not about the dumbness of users or negligence; the purpose should be to consider every case any user can input, and most of the time, some uncovered cases like this result in loopholes, and that's why we have so many invalid input error function in all sorts of the web development frameworks. <br>
I think it is **your job** to explore possible alternatives to solve this issue, and in my opinion, it's a fairly simple job to restrict the user to pay the exact amount rather than **any random number** he wants to pay.

**Comment by chethan58** [comment]
in the scenario u mentioned u said dues being 0 is wrong , then please tell me what it should be

**Comment by Divyanshsingh1910** [comment]
@chethan58  I am sorry if I wasn't clear in explaining myself; my concern was not primarily on the Dues becoming zero on the fact that more than the actual Due amount can be paid without any errors being raised and the final result also the same as if the original due amount is paid( which will Rs.0 if exactly the due amount is paid).<be>
I hope this clears up the confusion.
