### ISSUE TITLE
Ordering on extra item deleted by the manager

### ISSUE THREAD

**Issue by divc13** [Ashu3208/MessAutomationSystem#21]
Suppose these are the initial extras.
![image](https://user-images.githubusercontent.com/110289042/230557766-94f7b35e-b5b6-46ff-828e-b01ece6d40cd.png)

the mess manager removes the last item in the list.
![image](https://user-images.githubusercontent.com/110289042/230557819-6bfbacd3-0575-445a-b29f-5e540ef683ee.png)

But the item is still visible to the student because the page was not reloaded.
![WhatsApp Image 2023-04-07 at 12 24 58](https://user-images.githubusercontent.com/110289042/230557985-cc4a932d-01b7-4eb3-8482-b94306f0241a.jpg)

On booking this item, this error page loads.
![WhatsApp Image 2023-04-07 at 12 25 42](https://user-images.githubusercontent.com/110289042/230558104-5c7254b4-991c-4304-a1c2-e48da9a91967.jpg)

**Comment by Ashu3208** [comment]
Resolved

**Comment by Ashu3208** [comment]
Talking practically, these scenarios will not occur as students will book extras at the meal time while the manager would have added/removed the extras beforehand.
Also this is a completely different bug and so a new issue should be opened for it but right now we are not accepting any new bugs. However you are welcome to report new bugs  after the semester overs.
Please close the issue if satisfied
