### ISSUE TITLE
Mess manager has no access to students bill

### ISSUE THREAD

**Issue by divc13** [Ashu3208/MessAutomationSystem#22]
No option has been provided to the mess manager to view students bill. Hence it is misleading when we ask mess manager to clear dues of a particular student.

**Comment by Ashu3208** [comment]
@divc13 This is a nice suggestion and the feature of viewing student's bill can be added in the next version release of the software. For now, it seems that managers has to maintain a separate ledgers for students.
Please close the issue if satisfied
