### ISSUE TITLE
Accepting rebate request withdrawn by the student

### ISSUE THREAD

**Issue by divc13** [Ashu3208/MessAutomationSystem#30]
Suppose a student applies for a rebate request.

![WhatsApp Image 2023-04-07 at 15 02 01](https://user-images.githubusercontent.com/110289042/230586085-fb7749d1-af8a-4309-a242-8c357642a52e.jpg)

The manager views the rebate request.
![image](https://user-images.githubusercontent.com/110289042/230586694-698b637e-e829-44a3-b43e-94787c3e5007.png)

Before the manager takes any step, the student withdraws the request.
![WhatsApp Image 2023-04-07 at 15 02 53](https://user-images.githubusercontent.com/110289042/230586607-0fc9938a-26a3-4710-824d-0254650c55ae.jpg)

The manager accepts the request without reloading the page.

The website crashes.
![image](https://user-images.githubusercontent.com/110289042/230588044-479483b6-8f61-47c3-97db-593fe68858c8.png)

**Comment by Ashu3208** [comment]
Resolved
