### ISSUE TITLE
No limit on input size in name during signup

### ISSUE THREAD

**Issue by divc13** [Ashu3208/MessAutomationSystem#32]
Any amount of data can be inputted into the field of name.

![mynamesHTMLkhan](https://user-images.githubusercontent.com/110289042/230593434-f274e68d-7933-436e-bc67-68ded0c3d815.png)

![HTML_Singh](https://user-images.githubusercontent.com/110289042/230593415-0794339b-8242-4293-a621-f7a249275d1b.png)

**Comment by chethan58** [comment]
limit is 50 characters now. verify and comment if anything is wrong else close issue.
