### ISSUE TITLE
No details on Home page for manager

### ISSUE THREAD

**Issue by divc13** [Ashu3208/MessAutomationSystem#33]
The home page of mess manager is kept absolutely empty, and no data is provided.
![image](https://user-images.githubusercontent.com/110289042/230594629-8246d08b-19ac-483e-b725-8dcb4d44de3b.png)

**Comment by Ashu3208** [comment]
The home page of the manager serves no purpose and is just created to facilitate the login process. That's why there is no option in the navigation bar for Home page.

**Comment by divc13** [comment]
The home page gets loaded if you click on the logo of the your software. Also you can redirect to a different url to facilitate the login process.

**Comment by Ashu3208** [comment]
resolved
