### ISSUE TITLE
Single card for multiple orders of extras

### ISSUE THREAD

**Issue by pranjalsingh4550** [Ashu3208/MessAutomationSystem#34]
![two_orders_in_one_card](https://user-images.githubusercontent.com/96577548/230603145-07e1ed92-c842-457f-9488-589ec9e589d3.png)
It is possible that two extras are served at different places or at different times. But in orders for multiple dishes, there is only one card and all of the orders must be marked as served in one step. It is impractical to keep track of what has/has not been served manually.

**Comment by Ashu3208** [comment]
@pranjalsingh4550  This is not a issue as all the extras are generally served in continuation. 
Also, anywhere if you order something, different receipts are not made for different items. 
And more important point, at a time only 2-3 extras are served so it is not that hectic to keep track of what is served.
Please close the issue if satisfied

**Comment by pranjalsingh4550** [comment]
It is ok in theory, but there are as many as 4 counters (paneer, egg, dessert and biryani) in hall 2 on some days, and to serve two different paneer dishes, there can be a difference of upto 5 min in their preparation. I don't think the system is deployable, but it is alright for a course project.

**Comment by chethan58** [comment]
@pranjalsingh4550 i think this can be handled by adding check boxes for each item and adding another type of user who can only view the orders page and can only tick the check boxes, and this interface will be provided to those persons who are at extras counter , and the manager can close the order once all check boxes are ticked. we will add this if time permits , let me know if u think there is any problem in this.
