### ISSUE TITLE
Improper handling of long inputs to extras menu

### ISSUE THREAD

**Issue by pranjalsingh4550** [Ashu3208/MessAutomationSystem#36]
There is no character limit in the extras menu. The fields on the right appear outside the frame.
![long_extra_name_2](https://user-images.githubusercontent.com/96577548/230606945-93774475-722b-45b0-b83b-cf1b74ec06d4.png)
![long_exra_name](https://user-images.githubusercontent.com/96577548/230606957-b06c47e3-7ff5-4673-b88f-dce2dd336f32.png)

**Comment by Ashu3208** [comment]
The issue has been resolved.
