### ISSUE TITLE
No check on emails provided: one can register with email addresses of other users

### ISSUE THREAD

**Issue by divc13** [Ashu3208/MessAutomationSystem#4]
While registering as a student on the portal, one can enter any random email address and so one can enter the email address of other students and register. This is serious security and privacy issue.

![image](https://user-images.githubusercontent.com/110289042/230539562-7714b593-afd5-4989-ad8a-330dd9fe3cbe.png)

**Comment by chethan58** [comment]
changed , now otp will be sent to emails for checking emails provided. verify and comment if anything is wrong else close issue.

**Comment by divc13** [comment]
Recently checked the otp feature. Didnot work. Pls verify

**Comment by chethan58** [comment]
one recent merge was made and pushed without fixing conflicts by mistake that messed the latest version can you have a look at one of previous version (the one just before latest merge with message issue#4) .  I think u haven't updated .env while checking , do you? also have a look at issue #42
