### ISSUE TITLE
Menu Update Sends to Blank Page

### ISSUE THREAD

**Issue by Law1912** [Ashu3208/MessAutomationSystem#44]
Every time one updates the menu they are sent to this blank screen
![WhatsApp Image 2023-04-07 at 19 08 21](https://user-images.githubusercontent.com/106760756/230618855-abef1a46-550a-459b-ace3-a633ced110e7.jpg)
This also happens when one opens this section. It would be better if one menu opens as default here, and that the menu which was updated opens after reloading instead of blank page

**Comment by Ashu3208** [comment]
Fixed.

**Comment by divc13** [comment]
Upon adding items or deleteing them, the website redirects to Monday menu. The website should instead get redirected to the menu of the day in which the edit was made. Also, the when we get directed to Monday menu, the color of "MONDAY" does not get changed, as it should be.

**Comment by Ashu3208** [comment]
@divc13  Redirecting to Monday is not really a bug. Our Mess menu is such that you don't need to enter only one item at a time, you can enter all the menu at once separated by commas just like a table cell. 
Although, redirecting to the page in which the item was last added can be made in the further iterations of the software if that is really required.
Please close the issue if satisfied
