### ISSUE TITLE
Set precision correctly

### ISSUE THREAD

**Issue by rjvkr2021** [Ashu3208/MessAutomationSystem#45]
1.
![image](https://user-images.githubusercontent.com/105962042/230758623-6a69e686-bbde-41c0-801e-dbf6bcba2d8b.png)
In the last row
Name: hi Price: Rs. 9.9/- Quantity: 9
Total: **Rs. 89.10...01/-**
Set the precision correctly of the float (or double) variable you have used to store the value of **Total**.

2.
![image](https://user-images.githubusercontent.com/105962042/230758696-485b6f3f-1efe-4593-8d03-c0aaa3ba1c83.png)
If you are allowing the **Total**(described in the above issue) to be decimal, you must allow the input in the red box to be decimal. Or use integer variables at both places.

**Comment by chethan58** [comment]
now one can input integer only  . verify and comment if anything is wrong else close issue
