### ISSUE TITLE
Weird behaviour on signing up as a student after logging out as mess manager

### ISSUE THREAD

**Issue by rjvkr2021** [Ashu3208/MessAutomationSystem#46]
Firstly, the mess manager was logged in. Then, I logged out and signed up as a student. Instead of the default page for students upon signing up, the page for mess manager opened up, as shown in the below video.
https://user-images.githubusercontent.com/105962042/230759056-2b12261e-e917-4534-aaaf-8dd38b7bdcdc.mp4

**Comment by Ashu3208** [comment]
The issue has been resolved
