### ISSUE TITLE
Requesting Rebate for one day crashes the server

### ISSUE THREAD

**Issue by Law1912** [Ashu3208/MessAutomationSystem#47]
if the request is for the same date,
![image](https://user-images.githubusercontent.com/106760756/230771928-3adecfb8-58c6-45a5-8981-53e15fc50b47.png)
the server crashes.
![image](https://user-images.githubusercontent.com/106760756/230771949-2dc93b03-05d3-40eb-95cf-072729a1e241.png)

**Comment by Ashu3208** [comment]
The issue has been resolved.
