### ISSUE TITLE
No error message provided on registering with email id of domain other than iitk.ac.in

### ISSUE THREAD

**Issue by divc13** [Ashu3208/MessAutomationSystem#5]
On registering with a gmail account, the page got refreshed, without showing any error message. It was very misleading, and one cannot identify, if the registration was successful or not.
![image](https://user-images.githubusercontent.com/110289042/230540033-41d4b6de-e7e9-45a2-b300-1361e6cd2447.png)
![image](https://user-images.githubusercontent.com/110289042/230540042-553430d4-1557-4466-a449-615d1d54e83f.png)

**Comment by Ashu3208** [comment]
Resolved. Now only valid IITK email address is accepted
