### ISSUE TITLE
No check on user passwords

### ISSUE THREAD

**Issue by divc13** [Ashu3208/MessAutomationSystem#6]
There was no check provided on user passwords. 
One could just enter a space and set such trivial passwords.
This is a serious security issue.
![image](https://user-images.githubusercontent.com/110289042/230540845-decee075-4ad7-4d68-ba83-3ed5974524a7.png)
![image](https://user-images.githubusercontent.com/110289042/230540851-00816bc8-1be2-4fa8-af55-367105b443a9.png)

**Comment by chethan58** [comment]
Changed , Now Password must be between 8 and 24 characters long and include at least one uppercase letter, one lowercase letter, one number, and one of the following symbols: ! @ # $ % ^ & * ( ) _ +. verify and comment if anything is wrong else close issue.
