### ISSUE TITLE
Registering with same roll numbers

### ISSUE THREAD

**Issue by divc13** [Ashu3208/MessAutomationSystem#8]
when 2 different users register with same roll number, instead of some error message on the screen, the website gets redirected to some unknown error message popped on a black screen. This may be highly inconvinient for the users.

![image](https://user-images.githubusercontent.com/110289042/230546455-47020e94-311f-4122-98bf-c9c193c3975c.png)

![image](https://user-images.githubusercontent.com/110289042/230546462-0c43fe5c-18f4-4957-a73f-25b2cc2d0c57.png)

![image](https://user-images.githubusercontent.com/110289042/230546472-9b44a4ec-fc55-445e-8ea4-1d871326b324.png)

**Comment by Ashu3208** [comment]
Resolved
