### ISSUE TITLE
Registering with same email id

### ISSUE THREAD

**Issue by divc13** [Ashu3208/MessAutomationSystem#9]
When 2 users try to register with same email id, instead of showing some error on the same screen, an error message pops on a black screen, which is misleading.

![image](https://user-images.githubusercontent.com/110289042/230547086-ecdfa6ac-b2fd-4d93-b7f6-c19c721962e3.png)

![image](https://user-images.githubusercontent.com/110289042/230547472-ce47f610-64b2-4aba-965d-edf6b8cc560f.png)

![image](https://user-images.githubusercontent.com/110289042/230547097-605774ac-e5d5-47f7-b061-fc20e210c9c4.png)

**Comment by Ashu3208** [comment]
Resolved
